### ISSUE TITLE
Getting started without using third party auth?

### ISSUE THREAD

**Issue by gazhayes** [benadida/helios-server#103]
I've just got the django dev server up and running but (apparently) I can't do anything without setting up Google OAuth (which requires it to be *not* local). Am I missing something?

**Comment by benadida** [comment]
oy, it's possible that this has indeed happened given the change in Google's authentication to require tokens. I will look into a better long term solution for this.

In the meantime, if you're running on 127.0.0.1 or localhost, you can use the autologin option for local dev. See the method:

https://github.com/benadida/helios-server/blob/master/helios/views.py#L99

Basically, you go to http://localhost/autologin and it will auto log you in as the admin user. This only works if you're on localhost (obviously.)

**Comment by kniko** [comment]
You might as well change auth system to password.
### --setting.py ###

**change this**

AUTH_ENABLED_AUTH_SYSTEMS = get_from_env('AUTH_ENABLED_AUTH_SYSTEMS', 'google').split(",")

**to this**
AUTH_ENABLED_AUTH_SYSTEMS = get_from_env('AUTH_ENABLED_AUTH_SYSTEMS', 'password').split(",")

### --reset.sh ###

**add a password key to info**

echo "from helios_auth.models import User; User.objects.create(user_type='password',user_id='youremail@youdomain.net', info={'name':'Your Name','password':'yourpassword'})" | python manage.py shell

**Comment by shirlei** [comment]
In order to get kniko's setting working, it is necessary to fix a type error problem. See:

https://github.com/benadida/helios-server/pull/105

gazhayes, I'm able to use google OAuth. I have a credential set up as indicated in Ben's INSTALL.md and in Google Developers Console in Authorized JavaScript origins I have https://localhost:8000  and in Authorized redirect URIs I have http://localhost:8000/auth/after/

Of course this works only in localhost urls, but is enough to test the system.

**Comment by kniko** [comment]
Somewhere in stackoverflow I found the following line (insert in setting.py) which seems to be working. Not a Django expert here, so might it possible for that setting to introduce any unexpected problems? 

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

**Comment by shirlei** [comment]
I'm not a django expert myself kniko, but I stumbled upon your stackoverflow solution some time ago when I rebased my fork with upstream (to rebase with Ben's change to django 1.6.10) . My ldap module broke ( see https://github.com/shirlei/helios-server/commit/cf7059b8dad264ae8ecfea5c7a93c806d2815a47) and I got at that time the same json error. 

Instead of configuring something in settings.py, I've thought it would be better to change how I kept my user info on session (checking my code changes again, I think maybe I'll refactor it even more).  I don't know if setting a specific json library could bring problems in the future updates, but I think it maybe.

Ben have done something similar:

https://github.com/benadida/helios-server/commit/7ad65959acad5dedf3f12e358c574e4fcbf99a4b#diff-30c9084088bc0e30087876be1eed2a5d

But I'm maintaining my own fork, with several others changes, so for me it's convenient to change code. If a setting solves your problem in hand, why not? Let's see what Ben has to say (maybe this should be discussed on google groups https://groups.google.com/forum/#!forum/helios-voting !)
