### ISSUE TITLE
voting is not yet open

### ISSUE THREAD

**Issue by 15940260868** [benadida/helios-server#140]
Now, I have add trustees, and the screen shows "Next Step:compute encrypted tally", but the words under it are voting is not yet open.
I really dont't know how to open the voting.(even if it has missed the deadline)
Besides, when I choose private voting, I don't know how to add voters. I have uploaded the document(.csv), and the screen shows I have unloaded it(not yet processed), but I dont't know where I can find these voters.
I really need your help, and my mail is 313278392@qq.com.
Thanks!

**Comment by shirlei** [comment]
Hello! I think you could get more help using helios voting group: https://groups.google.com/forum/#!forum/helios-voting, since it is a more appropriate way to discuss helios usage and find questions that may already been answered  ;)
Regarding to processing your voters file, you have to run celeryd.

**Comment by benadida** [comment]
+1 to @shirlei so I will close this issue here to encourage discussion on the mailing list :)
