### ISSUE TITLE
Why we need this pre computable DLogTable table?

### ISSUE THREAD

**Issue by omidraha** [benadida/helios-server#180]
https://github.com/benadida/helios-server/blob/74c132e98dc6c523ff0ce113a31f985783285015/helios/workflows/homomorphic.py#L226

Also this [DLogTable](https://github.com/benadida/helios-server/blob/74c132e98dc6c523ff0ce113a31f985783285015/helios/workflows/homomorphic.py#L226) values will be same for all elections with [defined](https://github.com/benadida/helios-server/blob/8cc0c5a2019737d22024dc967c38d814e199c77a/helios/views.py#L49) public key.

Also, for a large voters, or for weighted election, the size of this table will be very huge, for example:
```
new_value = 10147875149082489599362678163739088009081109678105751099709577892608713833851421121481636738499395276247197106464992355096944883517851059830374817239446574716928287849960107288373353518385298193853787968016895117704198296220153192714389093212605793439452580342698036848850545187320412687585617933562026745301631553993338722970056389239277653782854565215503484628242626197385670744258188732585547675060739173297393302329991835096271951607346836440581560179328534586120324303717927805022648957771115337686020722801498417430697467884453655097037391464004950366399269977014120279278539583499104341479048649157541774621625L
size_new_value = (getsizeof(new_value)) # 300 byte
dlog_table_size = size_new_value * num_tallied
```

**Comment by benadida** [comment]
Helios pre-computes some discrete logs at the time of election tallying because it uses Exponential El-Gamal as its additive homomorphic system, and that requires computing a small-exponent discrete log for each question. Thus the pre-computation before tallying begins.

Yes, if you want to use Helios for a very large number of voters, this will take some time, but it should still be workable. Weighted elections... maybe you're working on a fork of Helios where Exponential El-Gamal isn't so great for you anymore.
