### ISSUE TITLE
Some proportional-representation option

### ISSUE THREAD

**Issue by wolftune** [benadida/helios-server#182]
Proportional Representation is specific to multi-seat elections. It involves de-weighting the preferences of those who get represented by the first or second winners (etc) so that the voting pool is represented broadly but still proportional to their numbers.

Single-Transferable Vote (STV) uses a ranked-ballot and has some issues but is still overall good because it provides PR.

Reweighted Range Voting (RRV) uses a score ballot and also achieves PR, and many voting theorists see it as a superior approach, especially since single-seat score voting fits with RRV for multi-seat (whereas single-seat STV is "instant runoff voting" which counts some voters' later preferences and ignores others in ways that are really problematic for single-seat elections).

Certainly, I prefer and encourage Score (or STAR) (see #116 and #181 ) and would thus like to see RRV for multi-seat elections.

**Comment by benadida** [comment]
Unfortunately, supporting STV and proportional-representation is quite difficult with end-to-end security of Helios, so I'm not planning on implementing those.

**Comment by wolftune** [comment]
I won't insist this be re-opened but two questions:

1. could you describe, if just very generally, why PR has anything to do with end-to-end security?

(Since completely anonymous paper ballots, one-per-voter, are usable for PR, there's no apparent security difference that I would have expected compared to any other voting system)

2. What about the prospect of having issues open and tagged with some label indicating that some qualified volunteer could work on this (but the main team may not have the resources currently) or similar sort of open-source contribution encouragement?

**Comment by benadida** [comment]
Hi @wolftune sorry for not previously providing more details.

- there's nothing inherently insecure about Proportional Representation. However, the specific end-to-end security features of Helios, where you as a voter get a tracking number of your vote and there's a publicly verifiable formula to check that, given all tracking numbers and the outcome, you get a guarantee the election was tallied correctly -- that's something that's very hard to do with proportional representation. The specific security properties of Helios are not something that can be fully abstracted away from the selected tallying approach, e.g. PR or otherwise. Helios is attempting to provide security features that typical in-person voting does not usually provide (end-to-end verifiability.)

- Because implementing this kind of work would be a very big architectural and cryptographic change, I'm not in favor of building these features into Helios at this time. Of course, anyone is free to fork and implement!

**Comment by nealmcb** [comment]
I am also dearly hoping for a convenient voting system that organizations can use which supports proportional representation! 

As Ben notes, the underlying issues and tradeoffs are complex, and should probably be discussed elsewhere. But for those who end up here via Google searches and the like, here is bit more background.
 
I think the reason that the current version of Helios doesn't easily support a Proportional Representation option is that it uses the homomorphic encryption approach.

The other widely-implemented approach to an end-to-end voting system, which supports any tally method, is a mixnet. It looks like [Zeus](https://github.com/grnet/zeus) might be a reasonable mixnet-based fork of Helios upon which to implement any tallying system, including for example [Proportional approval voting](https://en.wikipedia.org/wiki/Proportional_approval_voting) as I've implemented at [Proportional Representation Voting Methods, Data, and Auditing](https://github.com/nealmcb/pr_voting_methods).

Actually, version 1 of Helios was based on mixnets, but Helios then switched to homomorphic approaches to _"accommodate the need for votes having different weights according to the voter’s category"_, as discussed at [From Helios to Zeus](https://www.usenix.org/system/files/jets/issues/jets-0101-tsoukalas.pdf)

But that restricts the possible voting methods, because, as they go on to say:
> Homomorphic tallying operates directly on encrypted votes ... one cannot get results in the form of individual ballots as they were submitted.

On the other hand:
> mixnets shuffle the set of votes in a provably correct but practically untraceable way, therefore anonymizing it. The output is the same set of unencrypted ballots as they were before encryption and submission, only in random, unknowable order. Then any method of tallying can be applied to compute results.

See also [Running mixnet-based elections with Helios](https://www.usenix.org/legacy/events/evtwote11/tech/final_files/Bulens.pdf), though the code may not be available for that effort.

**Comment by glondu** [comment]
[Belenios](http://www.belenios.org), which was initially based on Helios, but has different implementation now, also supports mixnets (albeit experimentally).

**Comment by nealmcb** [comment]
FWIW, I see support for mixnets discussed at [Helios - Mixnet Support]( https://documentation.heliosvoting.org/verification-specs/mixnet-support):
> As of version 3.1, we plan to support mixnets in Helios

along with a page of implementation notes.

But 3.1 was released in 2011 and doesn't seem to mention mixnets.
