### ISSUE TITLE
How configure Apache with Helios?

### ISSUE THREAD

**Issue by Ramaniks** [benadida/helios-server#208]
Hello, I am trying to configure Helios to be accessed via Apache, I made the configuration, but this error occurring, can you help me? 
With "python manage.py runserver" is ok!!

In Apache error log:
ImportError: No module named site

wsgi.conf in Apache:
`WSGIScriptAlias /helios /var/www/apps/helios-server/wsgi.py
WSGIPythonHome /usr/local/lib/python2.7/dist-packages
WSGIPythonPath /var/www/apps/helios-server/ENV

<Directory /var/www/apps/helios-server/>
  <Files wsgi.py>
    Require all granted
  </Files>
</Directory>

<Directory /var/www/apps/helios-server/>
  Order deny,allow
  Allow from all
</Directory>
`

**Comment by shirlei** [comment]
Hi @Ramaniks !Are you using virtualenv, right? Assuming it is related to your helios directory, you could adjust similar to the following (I may be missing some of you path, so make the corrections when needed):

WSGIScriptAlias /  /var/www/apps/helios-server/wsgi.py
WSGIPythonPath /var/www/apps/helios-server:/var/www/apps/helios-server/ENV/lib/python2.7/site-packages

Are you in this group? https://groups.google.com/forum/#!forum/helios-voting ?
Since interest in helios is always growing, this kind of question would be nice there, I think, because it's easier to track later than here...

**Comment by Ramaniks** [comment]
Thank you @shirlei. It worked!!
