### ISSUE TITLE
No documentation on supported voting methods

### ISSUE THREAD

**Issue by Tanath** [benadida/helios-server#256]
This seems like a major oversight and should really be in the FAQ. How is anyone who cares about voting methods supposed to decide if they want to use Helios? How winners are decided matters. I could not find anything about which voting methods are supported aside from hints from a few methods mentioned in issues here.

**Comment by benadida** [comment]
Hi @Tanath. Helios supports first past the post and approval voting. I'll see if I can get to the FAQ, but am pretty busy at the moment. A PR would be welcome.

**Comment by BenSmyth** [comment]
First-past-the-post suffices for ranked voting: https://bensmyth.com/publications/2017-FPTP-suffices-for-ranked-voting/

**Comment by Tanath** [comment]
> First-past-the-post suffices for ranked voting: https://bensmyth.com/publications/2017-FPTP-suffices-for-ranked-voting/

That's an improvement, but it's a bit kludgey requiring extra effort after and not being supported in the program. Also, ranked voting has too many flaws. The methods I'm interested in are the ones that seem to be the best. Ie., [approval voting](https://www.electionscience.org/library/approval-voting-versus-irv/) and [score/range voting](https://www.rangevoting.org/).

**Comment by BenSmyth** [comment]
> > First-past-the-post suffices for ranked voting: https://bensmyth.com/publications/2017-FPTP-suffices-for-ranked-voting/
> 
> That's an improvement, but it's a bit kludgey requiring extra effort after and not being supported in the program. 

The kludge can be eliminated with a decent front-end. 

> Also, ranked voting has too many flaws. The methods I'm interested in are the ones that seem to be the best. Ie., [approval voting](https://www.electionscience.org/library/approval-voting-versus-irv/) and [score/range voting](https://www.rangevoting.org/).

The methods you're interested in follow from the above manuscript. Actually, those methods you mention are directly supported by Helios. At least, in theory, I don't know whether they've been implemented, but that shouldn't be too difficult---I believe all (or, at least, most) of the backend crypto is in the code base.

**Comment by aidamanzano** [comment]
Is STV supported by HELIOS?

**Comment by BenSmyth** [comment]
As per the above, Helios can be used for ranked voting, however, it doesn't scale (in the number of candidates) and the mixnet variant of Helios is preferable. 

"Neither Adidas...nor Bulens, Giry & Pereira...have released an implementation of Helios Mixnet. Tsoukalas et al...released Zeus as a fork of Helios 3.1.4 spliced with mixnet code to derive an implementation, and Yingtong Li released helios-server-mixnet as an extension of Zeus with threshold asymmetric encryption. Both implementations use multiplicatively-homomorphic asymmetric encryption, rather than additively-homomorphic encryption." (https://bensmyth.com/publications/2017-verifiability-Helios-mixnet/)
